### ISSUE TITLE
Problem in login with Facebook

### ISSUE THREAD

**Issue by Victorgf87** [CloudRail/cloudrail-si-ios-sdk#15] opened 2016-11-23 00:07 UTC
Hello, I have this problem:

I try to implement Facebook login with your sdk. When I execute
facebookClient.login() 
I get this error:

`ErrorUnknown("ServiceCode Error in function authenticate at 15, [*** -[__NSArrayM setObject:atIndexedSubscript:]: object cannot be nil]")`

I set my key with CRCloudRail.setAppKey, my ID and Secret for Facebook are correct.
I have tried all the initializers I found, but keep encountering that error u_u

Any help will be appreciated. Thank you very much :)

Edit: Sorry, forgot to say that I'm using Cloudrail 4.0.0, on xcode 7.3.1. Because any newer version says that it has been compiled with a newer version. 
Update Xcode is not an option.

**Comment by fel-cesar** [comment] 2016-11-23 14:32
Hello @Victorgf87 ,

    This issue you are having with Facebook SDK is probably due the update of Facebook API, this issue has been already fixed on newer versions of the SDK. Unfortunately we dont update older versions of the SDK anymore.
     To be sure this is the issue, you should download the latest version (separately from your current one) and run the example application checking if the error appears again, if so, then the problem is not just on the older version.
     In order to better help would be interesting to know the reason why you cannot update Xcode version, we can discuss it privately if you wish, just send an email to support@cloudrail.com.

**Closed** 2017-01-09 15:40 UTC
